name: Execute Quality Gate
on:
  workflow_call:
jobs:
  setupEnvironment:
    runs-on: ubuntu-latest
    steps:
      - name: Install UiTest prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
      - name: Run Gradle Tasks
        run: xvfb-run -a -s "-screen 0 1280x1024x24" ./gradlew detekt jacocoTestReport check --console=plain
      - name: Validate Documentation
        run: ./bin/validate_documentation.sh
