name: Continuous Integration
on:
  push:
    branches:
      - '*'
jobs:
  exec-ci:
    name: Execute CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/actions/setup-env
        with:
          setup-sonar: true
      - uses: ./.github/workflows/actions/exec-quality-gate
      - name: Trigger SonarQube via Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --console=plain
