name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  setup-environment:
    uses: ./.github/workflows/include-setup-env.yml
    with:
      setup-sonar: true
  exec-quality-gates:
    uses: ./.github/workflows/include-quality-gates.yml
    needs: [ setup-environment ]
  finalization:
    name: SonarQube
    needs: [ exec-quality-gates ]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SonarQube via Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --console=plain
