name: Continuous Integration
on:
  push:
    branches:
      - '*'
jobs:
  exec-ci:
    name: Execute CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # unshallow checkout, so sonarqube can do blame analysis
      - uses: ./.github/actions/setup-env
        with:
          setup-sonar: true
      - uses: ./.github/actions/check-quality-gates
      - name: Trigger SonarQube via Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --console=plain
