name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  setup-environment:
    uses: ./.github/workflows/includes/setup-env.yml
    with:
      setup-sonar: true
  exec-quality-gates:
    uses: ./.github/workflows/includes/exec-quality-gates.yml
  finalization:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SonarQube via Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --console=plain
