name: Automatic Release
on:
  workflow_dispatch:
    branches:
      - main
permissions:
  contents: write  # required to create releases
jobs:
  release:
    name: Create Release and Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/check-quality-gates
        # read version number from file, increment it, and pass to gradlew
        # write version file back; commit; tag
        # create GitHub release
        # matrix [macos, windows]:
        #    build artifact: run: ./gradlew packageDistributionForCurrentOS -Papp_version="${{ new_version }}"
        #    upload artifact to release

#  prepare-release:
#    runs-on: ubuntu-latest
#    name: Creating GitHub Release
#    steps:
#      - name: Create Release # https://github.com/marketplace/actions/create-tag-release
#        id: create_release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref_name }}
#          body: No changelog provided
#          draft: false
#          prerelease: false
#    outputs:
#      upload-url: ${{ steps.create_release.outputs.upload_url }}
#
#  build-and-upload:
#    strategy:
#      matrix:
#        os: [ macos-latest, windows-latest ]
#    runs-on: ${{ matrix.os }}
#    needs: prepare-release
#    name: Building and uploading compose artifact
#    steps:
#      - name: Log Info
#        run: echo "This job is now running on a ${{ runner.os }} / ${{ matrix.os }}; ref is ${{ github.ref }} and ref_name is ${{ github.ref_name }}"
#      - name: Checkout Code
#        uses: actions/checkout@v4
#      - name: Setup JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#      - uses: gradle/actions/setup-gradle@v4
#
#      - name: Execute Gradle
#        run: ./gradlew packageDistributionForCurrentOS -Plsc_version="${{ github.ref_name }}" -Plsc_gcalClientId="${{ secrets.GCAL_CLIENT_ID }}" -Plsc_gcalClientSecret="${{ secrets.GCAL_CLIENT_SECRET }}"
#
#      - name: Upload Release Asset for Windows
#        if: runner.os == 'Windows'
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.prepare-release.outputs.upload-url }}
#          asset_path: build/compose/binaries/main/exe/LocalSportsClub-${{ github.ref_name }}.exe
#          asset_name: LocalSportsClub.exe
#          asset_content_type: application/vnd.microsoft.portable-executable
#
#      - name: Upload Release Asset for MacOS
#        if: runner.os == 'macOS'
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.prepare-release.outputs.upload-url }}
#          asset_path: build/compose/binaries/main/dmg/LocalSportsClub-${{ github.ref_name }}.dmg
#          asset_name: LocalSportsClub.dmg
#          asset_content_type: application/x-apple-diskimage